name: option
version: 0.2.3
homepage: https://github.com/JosephMoniz/dart-option
description: >
  The Option typeclass inspired by Scala's implementation and Haskell's Maybe
  monad. Option is a composable and more expressive alternative to things that
  may be null on absence of value.
author: Joseph Moniz <joseph.moniz@gmail.com>
dependencies:
  either: '>=0.1.0 <0.2.0'